# Utiliser une image Docker avec Maven et Java
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Stages de pipeline
stages:
  - build
  - test
  - package

before_script:
 - docker info


# Étape 1: Compilation du projet
build:
  stage: build
  script:
    - docker build -t tourguide-app -f TourGuide/Dockerfile TourGuide/


# Étape 2: Lancement des tests (les tests de performances sont désactivés pendant la configuration initiale)
test:
  stage: test
  script:
    - docker run tourguide-app mvn -f /app/pom.xml test -Dgroups=!Performance # Désactivation des tests ici

# Étape 3: Construire les artefacts (package)
package:
  stage: package
  script:
    - docker run tourguide-app mvn -f /app/pom.xml clean package
  
  # Sauvegarde du fichier jar généré comme artefact
  artifacts:
    paths:
      - TourGuide/target/*.jar  # Le jar sera sauvegardé comme artefact
