# Utiliser une image Docker avec Maven et Java
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Stages de pipeline
stages:
  - build
  - test
  - package

before_script:
 - echo "Using Maven version $(mvn -v)"
 - docker info


# Étape 1: Compilation du projet
build:
  stage: build
  script:
    - docker build -t tourguide-app .

# Étape 2: Lancement des tests (les tests de performances sont désactivés pendant la configuration initiale)
test:
  stage: test
  script:
    - docker run tourguide-app mvn test -DskipPerformanceTests=true # Désactivation des tests ici

# Étape 3: Construire les artefacts (build)
package:
  stage: package
  script:
    - docker run tourguide-app mvn clean package
  
  # Sauvegarde du fichier jar généré comme artefact
  artifacts:
    paths:
      - target/*.jar  # Le jar sera sauvegardé comme artefact
