# Utiliser une image Docker avec Maven et Java
image: maven:3.8.4-eclipse-temurin-17

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

# Caching Maven repository to reuse dependencies
cache:
  key: "$CI_JOB_NAME"
  paths:
    - .m2/repository

# Stages de pipeline
stages:
  - build
  - test
  - package

before_script:
 - mvn --version

# Étape 1: Compilation du projet
build_job:
  stage: build
  script:
    # Temp: liste des fichiers dans TourGuide
    - ls -al TourGuide/
    - cd TourGuide # Accès au pom.xml
    - mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
    - mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
    - mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
    - mvn compile
  artifacts:
    paths:
      - .m2/repository

# Étape 2: Lancement des tests (les tests de performances sont désactivés pendant la configuration initiale)
test_job:
  stage: test
  script:
    - cd TourGuide # Accès au pom.xml
    - mvn --version
    - mvn test -DskipPerformanceTests=true  # Désactivation des tests ici
  dependencies:
    - build_job

# Étape 3: Docker: Construire de l'image après compilation
docker_build:
  stage: package
  image: docker:latest # Image Docker uniquement pour la partie Docker
  script:
    - docker build -t tourguide-app -f TourGuide/Dockerfile TourGuide/
  dependencies:
    - build_job
  
  # Sauvegarde du fichier jar généré comme artefact
  artifacts:
    paths:
      - target/*.jar  # Le jar sera sauvegardé comme artefact
