name: CI Pipeline

on:
    push:
        branches:
            - dev
            - master
    pull_request:
        branches:
            - master
            
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
                
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
                    
                    
            - name: Change to TourGuide directory
              run: cd TourGuide
                        
            - name: Install local dependencies
              run: |
                mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

                    
            - name: Build with Maven
              run: mvn -f TourGuide/pom.xml compile
              
    test:
        runs-on: ubuntu-latest
        needs: build
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
                
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
                   
            - name: Change to TourGuide directory
              run: cd TourGuide
                        
            - name: Install local dependencies
              run: |
                mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
                mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
                    
            - name: Run tests with Maven
              run: mvn -f TourGuide/pom.xml test 

    docker_build:
        runs-on: ubuntu-latest
        needs: test   


        steps:
          - name: Checkout source code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          
          - name: Check Docker Username
            run: echo "Docker Username: ${DOCKER_USERNAME_PARTIAL}*****" # Partiel pour vérification
            env:
                DOCKER_USERNAME_PARTIAL: "${{ secrets.DOCKER_USERNAME }}"

          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build Docker image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tourguide-app:latest -f TourGuide/Dockerfile .
            
          - name: Push Docker image to Docker Hub
            run: docker push ${{ secrets.DOCKER_USERNAME }}/tourguide-app:latest        