name: CI Pipeline

on:
    push:
        branches:
            - dev
            - master
    pull_request:
        branches:
            - master
            
            
jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
                
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
                    
            - name: Build with Maven
              run: |
                cd TourGuide
                mvn compile
              
    test:
        runs-on: ubuntu-latest
        needs: build
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2
            
            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'adopt'
                
            - name: Cache Maven packages
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                    ${{ runner.os }}-maven-
                    
            - name: Run tests with Maven
              run: |
                cd TourGuide
                mvn test 

    docker_build:
        runs-on: ubuntu-latest
        needs: test   


        steps:
          - name: Checkout source code
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build Docker image
            run:  |
                cd TourGuide
                docker build -t MichelleMairDocker/tourguide-app:latest -f Dockerfile .
            
          - name: Push Docker image to Docker Hub
            run: docker push MichelleMairDocker/tourguide-app:latest        